# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AwesomeChat
pod 'Firebase/Auth'
pod 'Firebase/Core'

  target 'AwesomeChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AwesomeChatUITests' do
    # Pods for testing
  end

end
